### PR TITLE
Repo maintenance

### PR DESCRIPTION
**Pull request by klab-systems**
- Update project to use chocolatey-au PowerShell modules rather than the archived au module
- Update Package metadata per feedback from the Chocolatey maintainers. Example: Remove all references of 32bit when there is no 32 bit installer, fix broken links etc.
- Syntax adjustments / removing aliases

### CODE REVIEW

**Comment by joshcooper** [comment]
Looks good to me. One request though, can you rebase your PR instead of pulling changes into your feature branch? The reason is it complicates the git history and makes git bisecting in the future more difficult. For example, this feature branch contains merge commits `bec73d6` and `4724c5f` which can be visualized as:

```
$ git log --pretty=format:'%C(yellow)%h%C(reset) %s %C(cyan)%cr%C(reset) %C(blue)%an%C(reset) %C(green)%d%C(reset)' --graph --date-order
* 0f70e68 Changing branch back to master, testing was successful 2 hours ago klab-sytems  (HEAD -> repo_maintenance, origin/repo_maintenance)
* d21fa2f changing branches for testing 2 hours ago klab-sytems 
* 0ffa249 commenting out TLS settings as we are receiving TLS errors in the run 2 hours ago klab-sytems 
* fd34c14 resolving spacing error in appveyor.yml 2 hours ago klab-sytems 
* fc055e8 changing branches back to master 2 hours ago klab-sytems 
*   4724c5f Merge pull request #43 from klab-systems/repo_maintenance 2 hours ago Kevin 
|\  
| *   bec73d6 merging changes from master 2 hours ago klab-sytems 
| |\  
| |/  
|/|   
| * 49b5ec1 Update appveyor.yml 2 hours ago Kevin 
* | 90d0408 AU: 1 updated - puppet-bolt [skip ci] https://gist.github.com/puppet-chocolatey-bot/07d26b70044a34c1d9aa5576057d515e/46dfa1b058fe5cc73ea5ba6c22d716d5db103839 18 hours ago Puppet Chocolatey Bot  (origin/master, origin/HEAD, master)
* | fb0e1d6 AU: 1 updated - puppet-agent [skip ci] https://gist.github.com/puppet-chocolatey-bot/07d26b70044a34c1d9aa5576057d515e/a36b99e4fe3da0ab0504299e2aa0264f244044c7 7 days ago Puppet Chocolatey Bot 
| * faa2bbb Updating package schema to the default generated from choco new 7 days ago klab-sytems 
| * 60f0743 removing alias's for readability 10 days ago klab-sytems 
| * 2f371e6 updating documentation where au is references with chocolatey-au 10 days ago klab-sytems 
| * d471d35 updating puppet-bolt. Normalizing method to match other packages. 10 days ago klab-sytems 
| * 6dc2d11 Updating puppet-agent. Removing uneeded license and verification information. Updating URLs in nuspec. Update to use chocolatey-au, PowerShell syntax, and remove unreferenced variable. 10 days ago klab-sytems 
| * 5c70cc0 Updating pe-client-tools, removing references to 32-bit. PowerShell Syntax adjustments 10 days ago klab-sytems 
| * f047b07 Updating pdk for chocolatey-au 12 days ago klab-sytems 
| * 60b0747 Removing Alias's from PowerShell script block in appveyor.yml 12 days ago klab-sytems 
| * a1d26a1 Update au_setup.ps1 to use new chocolatey-au module as au was archived; Fix PowerShell syntax 12 days ago klab-sytems 
|/  
* e70076d AU: 1 updated - puppet-agent [skip ci] https://gist.github.com/puppet-chocolatey-bot/07d26b70044a34c1d9aa5576057d515e/2e4b5886ee83104d36fcc64938f86ea44c89d89b 6 weeks ago Puppet Chocolatey Bot  (origin/gavin_fix_pdk_release)
```

I'd recommend rebasing your PR as:

```
$ git fetch origin
$ git rebase e70076d --onto origin/master
```

There will be conflicts needing resolving, so after resolving you'll need to `git add`, `git commit` and `git rebase --continue`

**Comment by klab-systems** [comment]
Rebased as requested with the provided instructions. Please let me know if any further changes are required.

**Comment by joshcooper** [comment]
sorry but still seeing merge commits like `c756fdb`. I think you'll need to `git rebase a1d26a1^ --onto origin/master` and resolve conflicts

**Comment by joshcooper** [comment]
Can you drop the testing commits that flipped the appveyor branch back and forth like

```yaml
   only:
-  - master
+  - repo_maintenance
```

Could you describe in your commit message for bb5b2c95d444e3f77172afa96bc404c6bd484740 why we're dropping the licenses? Did chocolatey change something on their end? Does the chocolatey UI pull licenses from somewhere else?

Commit cdcd0b47d2e07f47254307e44b9bfcf5ce63b693 introduced Windows line endings for some lines, but we seem to have a mix. Does it matter? 

```
$ find . -type f -name "*.ps1" -exec file {} \;       
./setup/au_setup.ps1: ASCII text
./update_all.ps1: ASCII text
./test_all.ps1: ASCII text
./automatic/pdk/tools/chocolateyinstall.ps1: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./automatic/pdk/update.ps1: ASCII text
./automatic/puppet-agent/tools/chocolateyinstall.ps1: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./automatic/puppet-agent/update.ps1: ASCII text
./automatic/pe-client-tools/tools/chocolateyinstall.ps1: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./automatic/pe-client-tools/update.ps1: ASCII text
./automatic/puppet-bolt/tools/chocolateyinstall.ps1: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./automatic/puppet-bolt/update.ps1: ASCII text
```

**Comment by klab-systems** [comment]
History has been cleaned up.

Commit message has provided more details as to why license.txt and verification.txt are being removed.

Regarding line endings ideally since this is running on Windows CRLF would be more appropriate. It appears to function the same whether it is LF or CRLF line endings. It's more common for CRLF to break linux than it is for LF to break windows.

**Review by joshcooper — APPROVED** [review]
Thanks @klab-systems! You're now our resident expert, so we may have questions for you during our next platform release in early June :grinning:

**Comment by joshcooper** [comment]
@donoghuc or @david22swan do you have questions/comments from the bolt & pdk perspective?

**Review by gavindidrichsen — APPROVED** [review]
As discussed Kevin, all looks good to me.

**Review by donoghuc — APPROVED** [review]
This is a great addition. Thank you for investing in this. 📦

**Review by binford2k — APPROVED** [review]

**Pull request merged**
